### ISSUE TITLE
no need for gform_enable_field_label_visibility_settings hook

### ISSUE THREAD

**Issue by izzygld** [adamhodson/wp_barebones#1]
[https://github.com/adamhodson/wp_barebones/blob/master/theme/adamhodson_sample_theme/functions.php#L165](https://github.com/adamhodson/wp_barebones/blob/master/theme/adamhodson_sample_theme/functions.php#L165)

As you can see  [here](https://docs.gravityforms.com/gform_enable_field_label_visibility_settings/) As of Gravity Forms 2.4, this functionality is part of the Form Editor and the hook has been deprecated.

Thanks

**Comment by adamhodson** [comment]
I'm actually not maintaining this one anymore. I have a much newer and more robust version of the framework I'm planning to release shortly so have been focusing entirely on that. I'll invite you to that repo once it's ready for public consumption.
